import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id:"1",
    title: "The Great Gatsby",
    image: "https://i.ibb.co/fkHsjnG/1-The-Great-Gatsby-Cover-1925-Retouched.jpg",
    author: "F. Scott Fitzgerald",
    price: 1099,
    newPrice: 899,
    discount: 18,
    Pages: 250,
    Language: "English",
    rating: 4.5,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fiction"
  },
  {
    _id: "2",
    title: "To Kill a Mockingbird",
    image: "https://i.ibb.co/gF7rWJj/book-cover-To-Kill-a-Mockingbird-many-1961.webp",
    author: "Harper Lee",
    price: 1299,
    newPrice: 999,
    discount: 23,
    Pages: 320,
    Language: "English",
    rating: 3.8,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fiction"
  },
  {
    _id: "3",
    title: "1984",
    image: "https://i.ibb.co/mTjWQS4/3-71-Nvk-Zxn-f-L-AC-UF1000-1000-QL80.jpg",
    author: "George Orwell",
    price: 1199,
    newPrice: 999,
    discount: 17,
    Pages: 328,
    Language: "English",
    rating: 2.7,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fiction"
  },
  {
    _id: "4",
    title: "The Lord of the Rings",
    image: "https://i.ibb.co/0X49MXc/4-33.jpg",
    author: "J.R.R. Tolkien",
    price: 249,
    newPrice: 199,
    discount: 20,
    Pages: 1178,
    Language: "English",
    rating: 1.9,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fantasy"
  },
  {
    _id: "5",
    title: "Pride and Prejudice",
    image: "https://i.ibb.co/JH7fztq/5-780143454229.jpg",
    author: "Jane Austen",
    price: 999,
    newPrice: 799,
    discount: 20,
    Pages: 432,
    Language: "English",
    rating: 4.5,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Non-Fiction"
  },
  {
    _id: "6",
    title: "The Catcher in the Rye",
    image: "https://i.ibb.co/tYkz6HP/6-download.jpg",
    author: "J.D. Salinger",
    price: 899,
    newPrice: 699,
    discount: 22,
    Pages: 224,
    Language: "English",
    rating: 3.3,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fiction"
  },
  {
    _id: "7",
    title: "Sapiens: A Brief History of Humankind",
    image: "https://i.ibb.co/V9tZPtR/751-Sn8-PEXwc-L.jpg",
    author: "Yuval Noah Harari",
    price: 149,
    newPrice: 119,
    discount: 20,
    Pages: 464,
    Language: "English",
    rating: 3.8,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Non-Fiction"
  },
  {
    _id: "8",
    title: "The Hobbit",
    image: "https://i.ibb.co/0Y0pkpF/8-The-Hobbit-trilogy-dvd-cover.jpg",
    author: "J.R.R. Tolkien",
    price: 999,
    newPrice: 799,
    discount: 20,
    Pages: 320,
    Language: "English",
    rating: 3.6,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fantasy"
  },
  {
    _id: "9",
    title: "Harry Potter and the Philosopher's Stone",
    image: "https://i.ibb.co/TKLv0zN/95165-He67-NEL.jpg",
    author: "J.K. Rowling",
    price: 1199,
    newPrice: 999,
    discount: 17,
    Pages: 336,
    Language: "English",
    rating: 2.9,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Non-Fiction"
  },
  {
    _id: "10",
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    image: "https://i.ibb.co/R22xSwC/10p90695-p-v8-aj.jpg",
    author: "C.S. Lewis",
    price: 8.99,
    newPrice: 6.99,
    discount: 22,
    Pages: 208,
    Language: "English",
    rating: 4.4,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fantasy"
  },
  {
    _id: "11",
    title: "The Book Thief",
    image: "https://i.ibb.co/SwQYvW0/1141-Lu-Ulddrh-L.jpg",
    author: "Markus Zusak",
    price: 109,
    newPrice: 89,
    discount: 18,
    Pages: 576,
    Language: "English",
    rating: 4.7,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fiction"
  },
  {
    _id: "12",
    title: "Brave New World",
    image: "https://i.ibb.co/tpnVPBr/12-Brave-New-World-First-Edition.jpg",
    author: "Aldous Huxley",
    price: 999,
    newPrice: 799,
    discount: 20,
    Pages: 288,
    Language: "English",
    rating: 4.3,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fiction"
  },
  {
    _id: "13",
    title: "The Da Vinci Code",
    image: "https://i.ibb.co/dcSN4qH/13the-da-vinci-code-589f9cee3df78c4758a2d9e7.jpg",
    author: "Dan Brown",
    price: 1299,
    newPrice: 999,
    discount: 23,
    Pages: 592,
    Language: "English",
    rating: 4.5,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Mystery"
  },
  {
    _id: "14",
    title: "The Girl on the Train",
    image: "https://i.ibb.co/TtkrnhR/14-The-Girl-On-The-Train-by-Paula-Hawkins-1200x1859.jpg",
    author: "Paula Hawkins",
    price: 899,
    newPrice: 699,
    discount: 22,
    Pages: 336,
    Language: "English",
    rating: 4.2,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Mystery"
  },
  {
    _id: "15",
    title: "Gone Girl",
    image: "https://i.ibb.co/FHjYFGT/159780753827666.jpg",
    author: "Gillian Flynn",
    price: 999,
    newPrice: 799,
    discount: 20,
    Pages: 432,
    Language: "English",
    rating: 4.6,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Mystery"
  },
  {
    _id: "16",
    title: "The Hunger Games",
    image: "https://i.ibb.co/6sJS9G2/162767052-SY475.jpg",
    author: "Suzanne Collins",
    price: 119,
    newPrice: 99,
    discount: 17,
    Pages: 384,
    Language: "English",
    rating: 4.7,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Mystery"
  },
  {
    _id: "17",
    title: "The Fault in Our Stars",
    image: "https://i.ibb.co/HD31dGV/17-F0945-E34-FBAA-4515-B625-4-E5-D27010518-Img400.jpg",
    author: "John Green",
    price: 109,
    newPrice: 89,
    discount: 18,
    Pages: 336,
    Language: "English",
    rating: 4.5,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Mystery"
  },
  {
    _id: "18",
    title: "The Harry Potter series",
    image: "https://i.ibb.co/DfxNywn/18images.jpg",
    author: "J.K. Rowling",
    price: 699,
    newPrice: 499,
    discount: 29,
    Pages: 4160,
    Language: "English",
    rating: 4.9,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fantasy"
  },
  {
    _id: "19",
    title: "The Power of Now",
    image: "https://i.ibb.co/ZKBzgxN/19download.jpg",
    author: "Eckhart Tolle",
    price: 139,
    newPrice: 109,
    discount: 21,
    Pages: 236,
    Language: "English",
    rating: 4.6,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Non-Fiction"
  },
  {
    _id: "20",
    title: "The Lean Startup",
    image: "https://i.ibb.co/myFNkkY/20-The-Lean-Startup-Eric-Ries-Buy-Online-Bookbins-1.png",
    author: "Eric Ries",
    price: 159,
    newPrice: 119,
    discount: 25,
    Pages: 336,
    Language: "English",
    rating: 4.4,
    cashOnDelivery:false,
    fastDelivery:true,
    categoryName: "Fantasy"
  }
];
